@startuml
skinparam monochrome true
skinparam shadowing false
skinparam style strictuml
skinparam LifelineStrategy nosolid
skinparam sequenceMessageAlign center
title Concurrent Requests in New System

participant Client as c
participant "Worker 1" as w1  
participant "Worker 2" as w2
database "Location Service" as ls

note over w1: starting with data d0
note over w2: starting with data d1

c -> ls: GET /data/d1
ls -> c: d1 @ w2
c -> w2: PUT /computation/c1 (result=d2; prereq d1)
c -> ls: POST /data/c1,d2 (w2)
w2 -> w2: PUT /computation-ready/c1
activate w2
...
c -> ls: GET /data/d0
ls -> c: d1 @ w2
c -> w1: PUT /computation/c2 (result=d3; prereq=d0,d2)
c -> ls: POST /data/c2,d3 (w1)
w1 -> ls: GET /data/d2
ls -> w1: d2 @ w2
w1 -> w2: GET /data/d2
...
c -> ls: GET /nodes
ls -> c: nodes
c -> w1: PUT /computation/c3 (result=d4; prereq=NULL)
c -> ls: POST /data/c3,d4 (w1)
w1 -> w1: PUT /computation-ready/c3
activate w1
w2 -> w2: POST /data/d2
deactivate w2
w2 -> w1: POST /data/d2
...
c -> ls: GET /data/d3
ls -> c: d3 @ w1
c -> w1: GET /data/d3
activate c
w1 -> w1: POST /data/d4
deactivate w1
w1 -> w1: PUT /computation-ready/c2
activate w1
...
w1 -> w1: POST /data/d3
deactivate w1
w1 -> c: POST /data/d3
deactivate c

@enduml
