@startuml
start
while (loop forever)
switch (request)
case (PUT /computation/*)
(A)
case (POST /data/*)
(B)
case (PUT /computation-ready/*)
(C)
case (GET /data/*)
(D)
endswitch
endwhile
-[hidden]->
detach

(A)
:store computation;
group stage computation
while (all prerequisites accounted for) is (no)
:select next unaccounted prerequisite;
if (prerequisite currently locally available?) then (yes)
:mark prerequisite available;
else (no)
:locate and issue request for prerequisite data (send GET /data/* request);
endif
endwhile (yes)
if (all prerequisites marked as locally available?) then (yes)
:set computation ready (send PUT /computation-ready/* to self);
else (no)
endif
end group
stop

(B)
:store data;
group Check if data is prerequisite to computation
if (data marked as prerequisite) then (yes)
:mark prerequisite available;
if (all prerequisites now accounted for) then (yes)
:set computation ready (send PUT /computation-ready/* to self);
else (no)
endif
else (no)
endif
end group
group Check if data has associated audience
if (data has associated audience) then (yes)
:send to audience;
else (no)
endif
end group
stop

(C)
:Access computation and all arguments from local Store;
:Run computation;
:Send returned data to self;
:Send returned data to self (send POST /data/* to self);
stop

(D)
if (data locally available?) then (yes)
:Return data to requester;
else (no)
:Add requester to audience for data;
endif
stop

@enduml
